
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: OpenBatteryInformation
        
    - name: Upload Application
      uses: actions/upload-artifact@v3
      with:
        name: OBI.exe
        path: OpenBatteryInformation/dist/windows

    - name: Upload Compiled File to Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: OBI.exe
